#Configuraciones generales
# server.port=9100
server.port=${PORT:0}

#Duracion de los tokens de acceso en segundos
access.token.duration=2678400 
refresh.token.duration=7776000

#Otras variables
service.notificaciones.email-nuevo-login=false