# server.port=${PORT:0}
server.port=8003
spring.mail.port=587
#Variabless de entonrno del servicio
service.validation-code-duration=20
service.two-factores-validation-code-duration=30
service.phone-sms-permited=true
service.whatsapp-permited=true
service.url-agregar-password=http://localhost:8080/agregar-password/username/codigo

#Documentation
springdoc.api-docs.enabled = true
springdoc.swagger-ui.enabled = true
 #swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
 #Define packeges to scan
#springdoc.packggesToscan=com.paquete1
springdoc.pathsToMath=/test/** , /support/** , /xyz/**